### ISSUE TITLE
Loading only one page to the PdfViewer

### ISSUE THREAD

**Issue by Nedayvozov** [pvginkel/PdfiumViewer#102]
Hello,

Is it possible to load only one page to the PdfViewer instead of loading a whole document?
Or alternatively, can we split PDF document into separate pages using your library?

Thanks,

**Comment by pvginkel** [comment]
I've extracted an interface from `PdfDocument` and added an implementation to the demo project that filters a number of pages from the provided document. Have a look at the attached commit for more information.
