### ISSUE TITLE
PDF Paging Issue

### ISSUE THREAD

**Issue by afmuser** [pvginkel/PdfiumViewer#104]
See attached sample check PDF. This PDF was created using a scanner. I spoke to the operator and he states that the check is in a stack of paper fed into the scanner.  The scanner knows to scan both sides of the check.  Other PDF types and other pages in this image work fine.  Some of the other images are scanned like this check and some are created programmatically

We are using PdfiumViewer v2.11.0

The error:
When paging to page 2, the viewer pages instead to page 3.  When paging from 3 to 2, it stays at 3. 

The code is correct I think:
pdfViewer1.Renderer.Page = page;

You can see the same result when running the above code in debug mode, when the above line executes and page has a value of 2 then Renderer.Page becomes 3.

We have 2 commercial viewers on site.  One works correctly and one works as above.

Buy the way, I was looking for a something like to but could not find it:
  pdfViewer1.ViewMode = ViewModes.SinglePage;

Is there a way to fix this?  

Regards, Lee
[sample_check.pdf](https://github.com/pvginkel/PdfiumViewer/files/804928/sample_check.pdf)

**Comment by pvginkel** [comment]
I've updated the algorithm. The old algorithm didn't perform well with documents with irregular page sizes, like yours. It seems to work a lot better now.

If you're still having problems, please reopen this ticket or create a new one.
