### ISSUE TITLE
FPDF_CreateNewDocument and FPDF_ImportPages are not implemented.

### ISSUE THREAD

**Issue by Nedayvozov** [pvginkel/PdfiumViewer#105]
I have some troubles with implementing the following methods:

public static IntPtr FPDF_NewDocument()
{
    lock (LockString)
    {
        return ImportsEx.FPDF_CreateNewDocument();
    }
}

public static bool FPDF_ImportPages(IntPtr destDoc, IntPtr srcDoc, string pageRange, int index)
{
    lock (LockString)
    {
        return ImportsEx.FPDF_ImportPages(destDoc, srcDoc, pageRange, index);
    }
}

They are not implemented at the moment in your library. However, they are very desirable for me.

I can not implement them for the following reasons:
1. NativeMethods class is not public.
2. PDFDocument does not contain an empty protected constructor and cannot be inherited. Also I do not have access to PdfFile because it is a private field.
3. I do not have access to PdfFile class because it is not public. It also does not have an empty protected constructor, and access to _document is limited.

**Comment by pvginkel** [comment]
These seem like generic PDF editor methods. The purpose of the PdfiumViewer is not to be a PDF editing library, but rather focuses on rendering it on screen.

If you need to edit PDF documents, please have a look at https://github.com/itext/itextsharp. This library implements such functionality and much, much more. I get the feeling what you're trying to do is merge multiple PDF files. See http://stackoverflow.com/questions/2233129/merging-pdfs-with-itextsharp for an example on how to accomplish this.
