### ISSUE TITLE
LoadLibrary is using the Ansi version

### ISSUE THREAD

**Issue by xanatos** [pvginkel/PdfiumViewer#108]
The LoadLibrary is using the Ansi Version of the method.

        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Ansi)]
        private static extern IntPtr LoadLibrary([MarshalAs(UnmanagedType.LPStr)] string lpFileName);

should be

        [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Unicode)]
        private static extern IntPtr LoadLibrary([MarshalAs(UnmanagedType.LPWStr)] string lpFileName);

otherwise if you have folders with Unicode names it won't work correctly (or like the CreateFileMapping use CharSet.Auto and LPTStr)

**Comment by pvginkel** [comment]
Thanks for the report. I've made the change.
