### ISSUE TITLE
Native pdfium.dll dlls not copied to project at nuget restore

### ISSUE THREAD

**Issue by ptr1120** [pvginkel/PdfiumViewer#111]
Hi,

thanks for PdfiumViewer it's a really good solution for rendering pdfs in a .net program.
When installing the PdfiumViewer nuget package to a project everything works fine (if I set the native pdfium.dll to be copied always to output directory).
But when I work with a version control system (e.g. git) and someone checks out my project referencing  PdfiumViewer the PdfiumViewer nuget package is restored via nuget restore, which does not copy the native pdfium.dll to my project folder (again) and therefore the build of my project fails. What about referencing the native libraries from the nuget folder, instead of copying them one time only at nuget install? See also: [Nuget refernce: Creating native packages](https://docs.microsoft.com/en-us/nuget/create-packages/native-packages),  [Nuget refernce: Including MSBuild props and targets in a package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package)

Best regards,
Peter

**Comment by pvginkel** [comment]
Can you please have a look at the comments made on #112?

**Comment by pvginkel** [comment]
As discussed in #112, I've decided to move the PDFium DLL out of the PdfiumViewer NuGet package and the new NuGet packages use the props files as described in #112.
