### ISSUE TITLE
Controls disabled in VS Toolbox

### ISSUE THREAD

**Issue by josemoliver** [pvginkel/PdfiumViewer#115]
The web controls appear disabled/greyed out. What am I doing wrong?

![toolbox](https://cloud.githubusercontent.com/assets/21282862/26279912/b7a660ae-3d8f-11e7-8502-c9a57ad1af01.png)

**Comment by josemoliver** [comment]
Nevermind, I thought this was a webform control.

**Comment by pvginkel** [comment]
No problem.
