### ISSUE TITLE
ASP.NET support

### ISSUE THREAD

**Issue by nathanaeljones** [pvginkel/PdfiumViewer#12]
Even when only one application is assigned to an application pool, multiple instances of that application are loaded during recycling. This presents problems with unmanaged DLLs that don't have a concept of app domains, but rather deal with some things at a process level. 

FPDF_InitLibrary, FPDF_DestroyLibary, FPDF_GetLastError, and FSDK_SetUnSpObjProcessHandler are the methods that could be problematic. 

It should be possible to modify FPDF_InitLibrary and FPDF_DestroyLibary to succeed even if the desired state (initialized, freed) is already achieved.

Callback registration, however, must stored in a thread-local manner, and re-registered before every P/Invoke call I.e, (FPDF_GetLastError, and FSDK_SetUnSpObjProcessHandler). 

If anyone sees another way around theses issues (other than modifying PDFium itself), please let me know.

**Comment by pvginkel** [comment]
I didn't think of this one yet. If dealt with stuff like this before and it shouldn't be an issue. I'll see whether I can fix this coming weekend.

**Comment by nathanaeljones** [comment]
Could we chat on Skype sometime? My handle is nathanaeldjones .

**Comment by pvginkel** [comment]
Yes, but probably not very soon because of a personal situation. I'm going
to get back to my outstanding issues the first chance I have and will
contact you to make an appointment for Skype.

**Comment by pvginkel** [comment]
A few changes have been made. Firstly, a few methods have been added to the Pdfium library to replace the loading mechanism with a reference counted mechanism. Instead of calling LoadLibrary directly, an `FPDF_AddRef

**Comment by nathanaeljones** [comment]
Thank you. Do you offer consulting services?
