### ISSUE TITLE
Feature Request - OnLinkClick() event

### ISSUE THREAD

**Issue by Shmoopy02** [pvginkel/PdfiumViewer#120]
Would be nice if there was an OnLinkClick() event callback so we can manually handle links to external docs or web pages in apps that use PDFiumViewer. For example, to open the link in another WPF or WinForms tab/window, which AFAIK the demo does not support. 

Seems like a simple thing to add for a fairly common use case?

**Comment by Shmoopy02** [comment]
Good example of this functionality in DevExpress PDF control:

https://documentation.devexpress.com/#WPF/CustomDocument115891

**Comment by pvginkel** [comment]
This is already possible. On the `PdfRenderer` class there is an event `LinkClick`. If you're using the `PdfViewer` class, you can access the `PdfRenderer` class through the `Renderer` property.

If you handle the click yourself, please make sure to set `e.Handled` to true to suppress the default handling of the event.
