### ISSUE TITLE
Feature enhancement - also copy fromat 

### ISSUE THREAD

**Issue by HofmansRVC** [pvginkel/PdfiumViewer#122]
When I copy a text to e.g. word only flat text is being copied. 
No format like bold font is copied.

I would very much like to have bold font, italic and other formatting options copied along with the plan text.

**Comment by pvginkel** [comment]
This would be very complex to implement. PDF is not trivially converted to text with format. In Windows, you'd implement this by either converting the text to RTF or to HTML, both of which are complex formats and not easily converted from PDF.

I'd welcome a PR, but it's not feasible to implement this feature. Sorry.
