### ISSUE TITLE
Bookmark PageIndex Always 0 with the Provided Sample.pdf

### ISSUE THREAD

**Issue by datauduong** [pvginkel/PdfiumViewer#123]
I am trying the PdfiumViewer.Demo project, which can show bookmark.

But the Sample.pdf that I have does not respond to the bookmark select

After Investigation futher, it is because the PageIndex = 0 for all bookmarks
Thanks.

**Comment by datauduong** [comment]
[Sample.PDF](https://github.com/pvginkel/PdfiumViewer/files/1191985/Sample.PDF)

I have re-test the demo, it is working with the provided Example 1 and Example 2, 
but when I Break at the Even (_bookmarks_AfterSelect) it does not triggered with the Sample.PDF attach.

**Comment by pvginkel** [comment]
I think this is a problem in PDFium. The bookmarks also don't work in Google Chrome. Funny thing though is that they do work in Foxit (from where the PDFium library comes). I've tried a few things in code like getting the action type of the bookmark, which returns unsupported.

I don't think there is anything I can do about this. Sorry.
