### ISSUE TITLE
Strange output when multiple shades of gray are near one another

### ISSUE THREAD

**Issue by Saberr43** [pvginkel/PdfiumViewer#124]
I have a process in place that converts a .pdf to a .tiff. 

In the .pdf, we have a logo that looks like this: http://imgur.com/aX9GeNi

When I convert the image of the pdf page to .tiff, the logo looks like this: http://imgur.com/Ilv8T51

I tried using the `PdfRenderFlags.Grayscale` flag, but this did not work.

**Comment by Saberr43** [comment]
*longingly looks back at post with soft eyes*

*sees that no one has come to my aid* 

https://media0.giphy.com/media/u2RGgVCSo2oow/giphy.gif

**Comment by pvginkel** [comment]
I'm sorry I'm late responding. I have a lot of difficult finding time to pick up tickets, but I'll try to find some time soon. It would be helpful if you can attach the original PDF so I can reproduce your issue.

**Comment by Saberr43** [comment]
No worries bud.

Here is a test .pdf you can use.
[Test.pdf](https://github.com/pvginkel/PdfiumViewer/files/1257408/Test.pdf)

Thank you

**Comment by Saberr43** [comment]
My apologies. The issue had to do with the way I was compressing the file.

Everything works now!

Thanks!
