### ISSUE TITLE
How to close the opened file

### ISSUE THREAD

**Issue by Shenyz163** [pvginkel/PdfiumViewer#127]
I can`t delete the pdf file after load in the pdfviewer. (this file is being used by another process).

**Comment by pvginkel** [comment]
The reason for this is that the PDF file is still in use. PdfiumViewer by default does not load the whole PDF file into memory to keep memory usage as low as possible. Instead, data is streamed into the control as necessary.

There are a few solutions to this I can think of:

* Don't try to delete the file while you have it open in the control. You can change it after you close it, but you do have to make sure you `Dispose()` the `PdfDocument` as this is not done automatically;
* You could copy the PDF file to a temporary location before you open it;
* You can load the whole PDF file into memory yourself using (something) like the following code:

```csharp
pdfViewer1.Document = PdfDocument.Load(new MemoryStream(File.ReadAllBytes(form.FileName)));
```
