### ISSUE TITLE
dbghelp.dll in "Without V8" version

### ISSUE THREAD

**Issue by GabMarc** [pvginkel/PdfiumViewer#129]
It's not really an issue but a question... I'm using the version without V8 because I need to support WinXP Let me tell you that it's working fine but I was wondering if the dbghelp.dll file is really needed and for what purpose? Is it needed in WinXP machines only? Thanks!

**Comment by pvginkel** [comment]
Uhm. Honestly? I don't know. I think when I tested Windows XP support, I found a problem which was solved by an updated `dbghelp.dll` file. However, I honestly can't remember how I got to that.

When I tested I did make sure to test on an unpatched version of Windows XP. It could very well be that a Windows XP installation with all SP's and automatic updates includes the correct version of `dbghelp.dll` and that that's the reason you don't have this issue.

**Comment by KakiLiang** [comment]
Hi, GabMarc, How did you do for supporting the XP? I have added the both folder x64 and x86 which is including the both files pdfium.dll & dbghelp.dll in my App. But when it run at XP, it still popup the error message "System.DllNotFoundException: Unable to load DLL ' Pdfium.dll'. Exception from HRESULT: 0xC000001D"." Thanks a lot!
