### ISSUE TITLE
Search: Wrong highlight position

### ISSUE THREAD

**Issue by NTBsMeep** [pvginkel/PdfiumViewer#131]
Hello
I integrated the PdfiumViewer in a project and it works almost perfectly. (Thanks for sharing!)
Unfortunately, if i search in the attached document (wrong.pdf), the search results are highlighted wrong. There is an offset of approximately x50, y115. In the second document (right.pdf), which i created to test if it's related on page size, it works perfectly.
I don't have the source of the wrong displayed pdf, so i can't test to generate with an older pdf version or other pdf generators.
To reproduce: Open the wrong.pdf document and search for "Handbuch", PdfiumViewer finds the two occurances, but highlight them wrong (one highlighting is even out of sight). In chrome it works perfectly, so i think its not pdfium.dll related.
Kind regards
[wrong.pdf](https://github.com/pvginkel/PdfiumViewer/files/1348707/wrong.pdf)
[right.pdf](https://github.com/pvginkel/PdfiumViewer/files/1348708/right.pdf)
![issue](https://user-images.githubusercontent.com/18145763/31075071-09964dd6-a774-11e7-8220-fb6674fc0fd3.png)

**Comment by NTBsMeep** [comment]
Hello,

I was able to solve the problem. The coordinates given by FPDFText_GetCharBox() need to be converted with FPDF_PageToDevice(). I added it directly after the GetCharBox call.

**Comment by pvginkel** [comment]
This has been solved in the referenced commit. I've used your sample PDF documents and they both give the correct result.
