### ISSUE TITLE
Change license to the Apache2 license

### ISSUE THREAD

**Issue by pvginkel** [pvginkel/PdfiumViewer#14]
I would like to change the license of the PdfiumViewer project to the Apache2 license. The Apache2 license puts less restrictions on how the PdfiumViewer library is used in other projects compared to the LGPL 3.0 license.

For this I need permission from people who made significant contributions to PdfiumViewer. If this isn't a problem for you, please leave a comment so that the license can be changed:

* @mafshin 
* @shameleo

**Comment by mafshin** [comment]
It's my honor to participate. :-)

On Sat, Apr 4, 2015 at 11:56 AM, Pieter van Ginkel <notifications@github.com
> wrote:

> I would like to change the license of the PdfiumViewer project to the
> Apache2 license. The Apache2 license puts less restrictions on how the
> PdfiumViewer library is used in other projects compared to the LGPL 3.0
> license.
>
> For this I need permission from people who made significant contributions
> to PdfiumViewer. If this isn't a problem for you, please leave a comment so
> that the license can be changed:
>
>    - @mafshin <https://github.com/mafshin>
>    - @shameleo <https://github.com/shameleo>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pvginkel/PdfiumViewer/issues/14>.
>



-- 
"Mathematics is the queen of the sciences and number theory is the queen of
mathematics."
--Gauss

**Comment by shameleo** [comment]
@pvginkel It's ok, no problem. Thx for asking.

**Comment by IgorMarkovic** [comment]
I see that you've changed the license. However the project home page on github still states LGPL.

**Comment by pvginkel** [comment]
Thanks for the catch. I've updated the readme file.
