### ISSUE TITLE
PdfDocument.Render producing blank pages

### ISSUE THREAD

**Issue by mrbastian** [pvginkel/PdfiumViewer#144]
I've been using the PdfDocument.Render method to convert PDF pages to images fairly reliably but I came across this PDF which is rendered as blank images.  The PDF seems to render successfully using various other tools including in chromium (x64 version 63.0.3239.132).  I'm using PDFViewer 2.13.0 and PdfiumViewer.Native.x86.v8-xfa.

Can anyone recommend any methods for troubleshooting further?

Parameters in this case are Render(<page>, 2550, 3300, 300, 300, true)

[79750-1213407-1990477.pdf](https://github.com/pvginkel/PdfiumViewer/files/1617272/79750-1213407-1990477.pdf)
![page2](https://user-images.githubusercontent.com/6626116/34752421-4c4b5b30-f580-11e7-9c7e-2dde870b6b6a.png)
![page1](https://user-images.githubusercontent.com/6626116/34752422-4c590ed8-f580-11e7-9027-84e31a359bd0.png)

**Comment by mrbastian** [comment]
Here's another example:
A 5 page PDF that pdfium renders fine on all pages except page 4.  On page 4, you can see the signature and some page noise, but all the text from the page is blank!  See motion.png for the output from the Render method.

How is it that chromium renders it perfectly, but pdfium has this problem? 

[Motion.pdf](https://github.com/pvginkel/PdfiumViewer/files/1627331/Motion.pdf)
![motion](https://user-images.githubusercontent.com/6626116/34893230-521c36e8-f7aa-11e7-81fc-13fb67b3af59.png)

**Comment by mrbastian** [comment]
I was thinking that the different behaviors between pdfium and chromium could be chalked up to not having a build from the latest pdfium source code -- the 32bit builds at https://assendelft.webathome.org/Pdfium/ have been failing since 12/4/2017.

I managed with some difficulty to get a local build working, but even with a fresh pdfium.dll I still get the same results as above -- a mostly blank page from pdfiumView+pdfium, and perfect results in chromium.

What else could I do to troubleshoot?

**Comment by mrbastian** [comment]
I'm closing this issue. I posted it to the pdfium project and the issue was identified and corrected https://bugs.chromium.org/p/pdfium/issues/detail?id=984

It was caused by a commit from 12/1/2017 and that commit was reverted today. If anyone is experiencing this issue you can either use a pdfium.dll built prior to 12/1/2017 or one after 1/15/2018.

**Comment by bkshah4** [comment]
I am still getting blank PDFs  even if i am using latest version. I have tried to switch to old stable version before 12/1/2017 but still the same. 
For the reference i am attaching the PDF which is causing blanks.
[1.pdf](https://github.com/pvginkel/PdfiumViewer/files/2366721/1.pdf)
