### ISSUE TITLE
Error in Windows XP

### ISSUE THREAD

**Issue by santiagoerueda** [pvginkel/PdfiumViewer#151]
Hello,

We are very happy with this library. We were able to implement it successfully and it works wonders, we are very grateful for your work. 

We have a small problem and I hope you can help us,
when we try to load a pdf file in demo project of PdfiumViewer in Windows XP SP2 32bits we recived this error:

> "The entry point of the InitOnceExecuteOnce procedure is not found in the dynamic link library KERNEL32.dll"

and after

> "Unable to load DLL file 'pdfium.dll': Unable to find the specified module. (Exception from HRESULT: 0x8007007E)"

We choose pdfium.dll without V8 functions and upgrade dgbhelp.dll in system32 folder but the errors persists.

What could it be? Thank you!

**Comment by santiagoerueda** [comment]
I solved it using a pdfium library compatible with Windows XP. You can download it from here:

https://github.com/151706061/PdfiumViewer/blob/master/Libraries/Pdfium/Windows%20XP%20compatible/x86/pdfium.dll

**Comment by roy19831015** [comment]
can you tell me how to solve the problem with XP?
I was confused by this problem for few weeks.
