### ISSUE TITLE
Some errors when build on windows.

### ISSUE THREAD

**Issue by bihuchao** [pvginkel/PdfiumViewer#166]
First, run `gn args .` to add some args, and "965 generated input errors found." and I ignored them.
Second, run `ninja pdfium`, "ninja: error: 'fpdfsdk/pdfiumviewer.cpp', needed by 'obj/pdfium/pdfiumviewer.obj', missing and no known rule to make it".

**Comment by kyawhpa** [comment]
Same error for me

**Comment by bihuchao** [comment]
@kyawhpa Have you fixed that now? If you made it, make me known. Thank you very very much.

**Comment by kyawhpa** [comment]
@bihuchao Nope, I could not fix it. I use one of the "PdfiumViewer.Native.xxxxx" from NuGet. Not trying to build by myself anymore.
