### ISSUE TITLE
Feature request: pdffonts-like functionality

### ISSUE THREAD

**Issue by ArloJamesBarnes** [pvginkel/PdfiumViewer#17]
Just that - being able to get a list of linked, embedded fonts and some technical details about them. I submitted this upstream too (PDFium plain...I may or may not submit it to PDF.js also) but figure the more eyes on it who might be interested, the better.

**Comment by pvginkel** [comment]
Does this mean this feature is not yet available in pdfium? This project is
just wrapper around pdfium and only exposes functionality that is available
in the stock pdfium project.

**Comment by ArloJamesBarnes** [comment]
Ah, I see I should have looked a little closer; I assumed your project was a fork. A wrapper would make just as much / more sense for a desktop application.
I do not believe this feature is in PDFium, although I may not be seeing the latest version if it updates with Chromium (I am running Debian stable, and it will take Jessie becoming the new stable in a few weeks for the Chromium update pipeline to start updating again). Honestly, I would be surprised if it was, it is kind of an unconventional feature for PDF viewers, but in my mind a light-weight, perhaps easy to implement, and useful one.

**Comment by pvginkel** [comment]
That makes sense.
