### ISSUE TITLE
Documents in landscape to printer.

### ISSUE THREAD

**Issue by pablot** [pvginkel/PdfiumViewer#19]
There is a problem with documents are printed in landscape mode. They are printed in normal mode with destroyed resolution.

**Comment by pablot** [comment]
Sorry, my mistake. Resolution and all settings are from printer. So changing it on printer is the solution. Word from M$ make it in other way. He set landscape mode on printer as is on document so i was thinking pdfium should do.

**Comment by pvginkel** [comment]
I've revisited this issue because of issue #23. The changes made there should solve your issue too. Please let me know how it works out for you.

**Comment by pablot** [comment]
Yea! Thank you very much for your work. I have a new issue with physical printer, but I post it in new thread.
