### ISSUE TITLE
Programmatically scroll to a particular spot on a page upon display

### ISSUE THREAD

**Issue by amadueke** [pvginkel/PdfiumViewer#21]
Hi Pieter, I believe we are almost at the end of the road here. If you are able to help out with this last requirement, it would be really great. Due to size very small size of the screen that my users will be using to view pdf documents, I'd like to go to scroll to a particular Y cordinate on a page upon displaying the page. So far, the methods that you have provide will take you to the top of a document or the bottom of one. You also created a new method to take a user to a specified page. I've tried to use the code pdfViewerBox.Renderer.SetDisplayRectLocation(new Point(0, -fieldposY)) to accomplish this goal, "-fieldposY" representing the spot that I want to go to. This works great when it's only one page but then when you have a multiple page document, it does not go beyond the first page. Perhaps because of the PDFRenderer. Please advise. Thanks

**Comment by pvginkel** [comment]
This really should just work though. Actually this is exactly what the algorithm does that jumps to a specific page. Have a look at https://github.com/pvginkel/PdfiumViewer/blob/37daed3fcd49cb14b26d66151b2daf02296358e7/PdfiumViewer/PdfRenderer.cs#L43-L88 for the details.

**Comment by pvginkel** [comment]
Have you had a chance to look at the code sample? I'm not sure how I can extend the project for your needs since what you are trying to do should already be possible.

**Comment by amadueke** [comment]
Hello Pieter, Sorry I was on vacation most of this week. Our business requirement ended up wanting the top of each appended PDF page displayed instead of specifying a certain point on a page. I was able to write that code to make that happen. I have not had a lot of time to delve further and see if I can actually specify a certain point and take a user there. Thanks for checking and for all the help.
