### ISSUE TITLE
Navigation on content by links in PDF.

### ISSUE THREAD

**Issue by InfSource** [pvginkel/PdfiumViewer#25]
The Pdfium supported the the definition of links on a page that is very convenient to navigate through content.

I think it can be done by determining the list of rectangles of the links on the corresponding page.

I've written the following code that returns the associative array with areas (rectangles) on page and appropriate link address (page numbers):

            private Dictionary<Rectangle, int> GetLinks(IntPtr document, IntPtr page, double width, double height)
            {
                Dictionary<Rectangle, int> linckAreas = new Dictionary<Rectangle, int>();

                int startPos = 0;
                IntPtr linkAnnot;

                while (NativeMethods.FPDFLink_Enumerate(page, ref startPos, out linkAnnot))
                {
                    IntPtr pdfDest = NativeMethods.FPDFLink_GetDest(document, linkAnnot);

                    if (pdfDest == IntPtr.Zero)
                        continue;

                    int index = (int)NativeMethods.FPDFDest_GetPageIndex(document, pdfDest);

                    NativeMethods.FS_RECTF rect = new NativeMethods.FS_RECTF();
                    _RectCallbacksHandle = GCHandle.Alloc(rect);

                    if (NativeMethods.FPDFLink_GetAnnotRect(linkAnnot, out rect))
                    {
                        int deviceX, deviceY;

                        NativeMethods.FPDF_PageToDevice(page, 0, 0, (int)width, (int)height,
                            0, rect.left, rect.top, out deviceX, out deviceY);
                        linckAreas.Add(
                            new Rectangle(deviceX, deviceY, (int)(rect.right - rect.left),
                            (int)(rect.top - rect.bottom)), index);
                    }
                }

                return linckAreas;
            }

Could you help me embed this logic into your project?

**Comment by pvginkel** [comment]
This has been implemented. I've also added support for URI's.
