### ISSUE TITLE
Resolution is off in bitmap output

### ISSUE THREAD

**Issue by tskarman** [pvginkel/PdfiumViewer#28]
From what I've gathered, the page dimensions as reported by PdfiumViewer are off by a factor of 1.3 which ultimately leads to an incorrect size of the bitmap output.

The default DPI value for PDF documents is 72 DPI. I used ImageMagick output to confirm that that is also true for my test PDF file.

It looks like you are getting the page dimensions from the native library. So I am not sure whether this actually is something you can do anything about.

Here is what I am currently doing to work around that (and to output resolutions other than 96 DPI):

    var dpiTarget = 150;
    var pdfDpiDefault = 72D;

    float systemDpiX;
    float systemDpiY;
    using (Graphics graphics = Graphics.FromHwnd(IntPtr.Zero))
    {
        systemDpiX = graphics.DpiX;
        systemDpiY = graphics.DpiY;
    }
    
    var pageWidthPixels = (int)pdf3.PageSizes[0].Width;
    var pageHeightPixels = (int)pdf3.PageSizes[0].Height;

    var cX = systemDpiX / pdfDpiDefault;
    var cY = systemDpiY / pdfDpiDefault;

    var dpiX = (int)(dpiTarget * cX);
    var dpiY = (int)(dpiTarget * cY);

    var factorX = dpiX / systemDpiX;
    var factorY = dpiY / systemDpiY;
    
    var renderWidthPixels = (int)Math.Round(pageWidthPixels * factorX, 0, MidpointRounding.AwayFromZero);
    var renderHeightPixels = (int)Math.Round(pageHeightPixels * factorY, 0, MidpointRounding.AwayFromZero);

    using (var image = pdf3.Render(0, renderWidthPixels, renderHeightPixels, dpiX, dpiY, false))
    {
        // ...
    }

I also tried using the other Render signatures for getting the correct output resolution (i.e. `Graphics.FromImage(bitmap)` but using a value other than 96 dpi screwed up the output (e.g. incorrect font sizes and/or incorrect output size (lots of white space)). So I think that something is not quite right about the transforms in that method.

**Comment by pvginkel** [comment]
I'm not really sure what you mean. Are the dimensions of the output image different from the dimensions you specify to the `Render` call? That shouldn't be. For the `Render` overload that returns an `Image`, the height and width are send to the Pdfium library verbatim. The X and Y DPI aren't even used.

**Comment by pvginkel** [comment]
Have you had a change to look at my response?

**Comment by bryjamus** [comment]
I attach to the subject because I have problem with rendering page as image with resolution different than 96 dpi. When I set ````dpiX```` and ````dpiY```` as 300 final image still has vertical and horizontal resolution 96 dpi. I think that problem is in method: ````RenderPDFPageToBitmap```` in ````PDFFile```` class. You have ````dpiX```` and ````dpiY```` parameters but not using them.
