### ISSUE TITLE
Missed parameters in the RenderPDFPageToBitmap() method.

### ISSUE THREAD

**Issue by Nedayvozov** [pvginkel/PdfiumViewer#29]
Hello,

I'm using a custom printing form with additional parameters to print a document so I use RenderPDFPageToBitmap() method from PdfFile class instead of the standard Print(). But this method doesn't use dpiX and dpiY parameters, so I can't choose the quality of rendering.

Thanks,

**Comment by pvginkel** [comment]
Well, the Pdfium library doesn't take DPI information in any of it's calls (at least not the ones I'm using). Couldn't you render in a higher resolution and scale down once you print?

Why are you custom printing? Is there functionality missing in the `PdfPrintDocument` that you need? The `PdfPrintDocument` class only uses public methods. You could also just copy the code of that class into your project and make the modifications in that way.

**Comment by pvginkel** [comment]
Have you had a chance to look at my response?

**Comment by Nedayvozov** [comment]
Hello,
This is not an issue. Besides that now I'm using the PdfPrintDocument.
Sorry for delay.

**Comment by pvginkel** [comment]
Not a problem. Thank you for your response.
