### ISSUE TITLE
Go to the next / previous page.

### ISSUE THREAD

**Issue by Nedayvozov** [pvginkel/PdfiumViewer#30]
Hello,

I found the issue, which is reproduced by the following steps:

1. Load pdf that contain consecutive three portrait pages and three landscape pages
2. Change zoom to 50%
3. Invoke the next code 3 times.

        public void GoToNextPage()
        {
            _renderer.Page++;
        }

The viewer displays page 4, that is landscape.

4. Try to invoke the next code:

        public void GoToPreviousPage()
        {
            _renderer.Page--;
        }

Actual result: the page is not changed.
Expected result: the viewer displays page 3.

Thanks,

**Comment by pvginkel** [comment]
I've updated the page number algorithm to take the current zoom level into account. It's now a lot more predictable.
