### ISSUE TITLE
FitHeight for landscape pages.

### ISSUE THREAD

**Issue by InfSource** [pvginkel/PdfiumViewer#34]
FitHeight does not work correctly for page that is in Landscape.

**Comment by pvginkel** [comment]
Could you please provide a bit more information? I have created a document with a few pages in landscape mode and opened this with the demo application part of the PdfiumProject. That has a default mode of FitHeight. It looks fine to me. Could you please provide the steps to reproduce the issue you're seeing and a description or print screen of the exact problem?

**Comment by Nedayvozov** [comment]
Please see the screenshot http://myscreenshot.info/i/0006/722311438685678628394694885246.png
FitHeight is not works correctly for the landscape page.

**Comment by pvginkel** [comment]
Can you please also provide the PDF document you've used to create this screenshot?

**Comment by Nedayvozov** [comment]
PDF: https://www.dropbox.com/s/0n15k86ctki5x9l/test.pdf?dl=0

**Comment by pvginkel** [comment]
So, a bit of explanation on this. The fit height and fit width functionality looks at the maximum height and maximum width of **all** pages to determine the zoom level. The problem you're encountering is that the maximum width is taken from the landscape pages, and the maximum height is taken from the portrait pages. Both fit width and fit height will give you non intuitive results if you're on a specific page.

I guess how you would like this to work is that the zoom level is adapted based on the current page. However, this would be very confusing. That would e.g. imply that the zoom level would adapt automatically when you scroll through pages, which is very confusing.

The behavior as currently implemented is exactly what Foxit does and I think this is reasonable, so I'll leave it as is.
