### ISSUE TITLE
Recompile native DLL to avoid cut off embedded GIF image regression

### ISSUE THREAD

**Issue by rvanicek** [pvginkel/PdfiumViewer#37]
A regression was introduced to the google sources https://code.google.com/p/chromium/issues/detail?id=478164. It has been corrected since, only pdfium.dll needs to be recompiled.

**Comment by Hallaghan** [comment]
It seems that the newer versions of Pdfium have resolved this bug. @pvginkel do you think you could update the pdfium.dll offered on the nuget package of pdfium to the newer version? 
I'd compile it myself but admitedly, I have not been successful in doing so.
Apreciated and thanks for your work.

**Comment by pvginkel** [comment]
I've already had a look at this, but certain changes in the Pdfium code base made this a non trivial update. I'll have a look at this again, but this will take a considerable amount of time and I'm not sure when I have the chance.

**Comment by Hallaghan** [comment]
@pvginkel  Thank you for taking your time to look into it. If it might be of some help, would it be possible to use the pdfium dll version just after the bug was fixed, instead of the latest one? Or was it then that these compatibility breaking changes were introduced?

**Comment by pvginkel** [comment]
Sorry for the delay. I took another step at building Pdfium and finally got it to build. One major change is that this version is not compatible with Windows XP anymore because changes to the source code prevent it from being built with the Windows XP toolset.

I've pushed version 2.8.0.0 to NuGet.

**Comment by pvginkel** [comment]
I've automated building the PDFium library. Please have a look at [PdfiumBuild](https://github.com/pvginkel/PdfiumBuild) for the project. This application runs on a build server and produces output daily. If in the future you need an up to date version of the PDFium library, you can pull it off of the build server yourself, or use the project to to a build on your local machine.
