### ISSUE TITLE
Rendering (not filling) form fields

### ISSUE THREAD

**Issue by IanYates** [pvginkel/PdfiumViewer#38]
Does PdfiumViewer support rendering form fields?
Example: 
http://www.humanservices.gov.au/spw/health-professionals/forms/resources/pb154-1507en.pdf

(it's a PDF document from Medicare Australia with some PDF form fields on it)

I can fill out the form using Adobe, Nitro or even my own PDF toolkit (Essential Objects PDF).  What I'd like to do is then render that PDF with its filled-in information.

There's an issue on here - #22 - which implies this isn't supported, but that issue more talks about filling in form fields rather than rendering them.  I'm just trying to confirm whether or not rendering is actually supported (as I've got the filling aspect already covered)

Thanks!

Ian

**Comment by pvginkel** [comment]
I'm not really sure. Have you tried this already?

**Comment by IanYates** [comment]
Sorry, I should have been clear.  Yes I have tried it :)  
The field values weren't displayed unfortunately.

I couldn't see any method overloads or other relevant settings so my next course of action was to search through the issues and then open one myself.    (thanks for responding so quickly!)

**Comment by pvginkel** [comment]
I'll have a look at this. Can you please provide me with an example and the
expected result? That'll help a lot solving this issue.

**Comment by IanYates** [comment]
Sure - I can send the PDF here, or you can grab it from that link (I figure you might trust the Aust government more than some random stranger on the Internet).

I've put a PDF here for you
https://onedrive.live.com/redir?resid=1564C2E9CA39DE26!273701&authkey=!ACt_7nDiPBglxOQ&ithint=folder%2cpdf
The original from Medicare is there - all fields are blank waiting to be completed.  
The other file is a filled in copy saved via Adobe Reader.

I appreciate your help - happy to test things here.

**Comment by pvginkel** [comment]
Thanks. I'll let you know what I find.

**Comment by IanYates** [comment]
:+1: splendid :)

**Comment by IanYates** [comment]
Wow - thank you.  I'll give it a try during the week.  Cheers :beers:
