### ISSUE TITLE
ZoomIn functionality

### ISSUE THREAD

**Issue by Saran88** [pvginkel/PdfiumViewer#39]
The current ZoomIn function will not retain the current page in the render's view. The Mouse Scroll function will calculate the current mouse location, which works fine, but the zoomin function for buttons should be modified to stay in the current sheet in view.

EX: Open a document with say 7 pages. Scroll down to the last page and zoom in multiple times, you will end up back at page 3 or 2.

Current Workaround I have implemented, create a method to return the current page bounds in the PdfRenderer class and then create a new zoomin method in the PanningZoomingScrollControll class to accept the bounds from the current page and zoom in.

It would be nice if there was either a method to call to do this or have the zoomin function do this by default.

**Comment by singingsang** [comment]
can you please provide workaround you did for zoom issue- a piece of code and where it was amended? It would help implementing this plugin.

**Comment by Saran88** [comment]
@singingsang You can find the necessary temporary fix at [https://github.com/Saran88/PdfiumViewer/commit/939cb3e8ef065fa7ac37247e744748f4f6ba64d2](url)

**Comment by singingsang** [comment]
Thank you Saran for your prompt fix, really appreciate it.

**Comment by pvginkel** [comment]
@Saran88 I've used your commit and merged. I've changed it though to be transparent (so the `ZoomIn` overload has been removed), so the logic has been moved to the `Zoom` setter, to an overload in `PdfRenderer`.
