### ISSUE TITLE
Memory utilization in WPF

### ISSUE THREAD

**Issue by sbrickey** [pvginkel/PdfiumViewer#42]
I am looking for recommendations (or fixes if need be) for rendering PDF's using native WPF controls, without unnecessarily inflating the application's memory footprint.

Testing environment:
- PDF is 615kb, containing 8 pages of text scanned as an image (from some sort of multi-function printer/scanner). Specific file cannot be shared due to sensitivity, but does not appear to be abnormal.
- WPF application using 4.5.1 framework

To isolate the impact as much as possible, I have made the following changes to the PDFDemo provided:
XAML:

```
    <ScrollViewer Grid.Row="4" Grid.Column="0" Grid.ColumnSpan="2">
        <StackPanel>
            <Image x:Name="imageMemDC1" />
            <Image x:Name="imageMemDC2" />
            <Image x:Name="imageMemDC3" />
            <Image x:Name="imageMemDC4" />
            <Image x:Name="imageMemDC5" />
            <Image x:Name="imageMemDC6" />
            <Image x:Name="imageMemDC7" />
            <Image x:Name="imageMemDC8" />
        </StackPanel>
    </ScrollViewer>
```

XAML.CS:

```
    var imageMemDC = this.FindName(String.Format("imageMemDC{0}", i)) as System.Windows.Controls.Image;
```

so basically, instead of one image control, I've got one for each of the pages... then instead of rendering each page over the previous image, I render them to individual controls.

---

These changes alone are sufficient to reproduce the memory consumption I'm seeing, though in my application I've also adjusted the width/height to be the PageSize.Width \* 4 and PageSize.Height \* 4, to produce "crisp" images. Using the default pagesize (with 96 dpi) seems to generate blurry text. Again, not a huge difference, except that the memory consumption is larger with my changes, due to the larger image resolution.

---

Test Results:

The application's memory footprint starts at ~43mb (TaskMgr showing Private Working Set). VMMap shows that the total private bytes are 75MB, while private WS bytes is 45MB; of this, "Private Data" accounts for 45MB of the private memory, and 30MB of the private WS memory.

Once the PDF is loaded, TaskMgr shows the process to consume 80MB (private working set), VMMap shows 116MB total private, 83MB private WS, and private data accounts for 66MB of private and 50MB of private WS.

Once the pages are rendered, TaskMgr shows the process to consume 90MB, VMMap shows 130MB total private, 93MB private WS, and private data accounts for 77MB of private and 60MB of private WS.

Using the higher resolution (pagesize.width_4 x pagesize.height_4), the same PDF rendered consumes 311MB of memory (TaskMgr private WS), with VMMap showing 350MB total private, 317 private WS, and private data accounting for 299MB private and 282MB private WS.

---

I have also considered other approaches:
- the PdfiumViewer nuget package includes two WinForms controls, the PdfViewer and PdfRenderer... by including them in the WPF application (wrapped in a WindowsFormHost control), the same file is rendered with no notable increase in memory usage. During rapid resizing of the application/controls, I noticed unpainted areas of the window (black areas while expanding the window), which leads me to suspect that the WinForms controls use GDI to repaint the PDF on scroll/resize/etc; I suspect that this is done directly from file each time, instead of keeping the file/pages in memory.

---

From searching for causes/solutions, I found https://github.com/pvginkel/PdfiumViewer/issues/6 which suggests that perhaps the Render method (used by the WPFDemo code to render the PDF) was originally intended for saving pages to files. In this case, I would question what better alternatives there may be, for rendering pages of the PDF in native WPF controls.

---

I have attached screenshots of the difference between rendering with the PDF's PageSize dimensions, and PageSize \* 4.
![at pagesize](https://cloud.githubusercontent.com/assets/11029848/8875660/d6f2fcc4-31e8-11e5-8d72-b8a4542b06c0.png)
![at 4x x 4x](https://cloud.githubusercontent.com/assets/11029848/8875664/e0372fee-31e8-11e5-9359-df3df5ecf8d6.png)

**Comment by sbrickey** [comment]
Have been able to address issue.

Found this SO question, posting a similar issue: http://stackoverflow.com/questions/6271891/net-memory-issues-loading-40-images-memory-not-reclaimed-potentially-due-to

Basically the general idea is that the BitmapSource keeps a duplicate copy of the data around in memory (src: http://code.logos.com/blog/2008/04/memory_leak_with_bitmapimage_and_memorystream.html)

For Pdfium, the solution is to Render to Image (even at the higher resolution), then Save to memorystream (I chose PNG format, since the size/quality ratio is pretty good)... then reset position, and use a stream wrapper (http://code.logos.com/blog/2009/05/wrappingstream_implementation.html) to dispose (and GC) the original bytes, after it's been copied into the WPF components.

The changes interfered with some of the async stuff, so as a quick workaround I just kept things synchronous (since I just wanted to confirm the memory footprint, not worry about max thread performance)... but here's the code change:

                for (int i = 1; i < pdfDoc.PageCount; i++)
                {
                    var imageMemDC = this.FindName(String.Format("imageMemDC{0}", i)) as System.Windows.Controls.Image;

                    var width = Convert.ToInt32(pdfDoc.PageSizes[i].Width);
                    var height = Convert.ToInt32(pdfDoc.PageSizes[i].Height);

                    var image = pdfDoc.Render(i, width, height, 96, 96, false);
                    var imgSource = new System.Windows.Media.Imaging.BitmapImage();
                    using (var msImagePNG = new System.IO.MemoryStream())
                    {
                        image.Save(
                            stream: msImagePNG,
                            format: System.Drawing.Imaging.ImageFormat.Png
                        );
                        msImagePNG.Position = 0;
                        using (var msWrapper = new WrappingStream(msImagePNG))
                        {
                            imgSource.BeginInit();
                            imgSource.CacheOption = BitmapCacheOption.OnLoad;
                            imgSource.StreamSource = msWrapper;
                            imgSource.EndInit();
                            imgSource.Freeze();
                        }
                    }
                    imageMemDC.Source = imgSource;

**Comment by sbrickey** [comment]
So... if after rendering the image, I set the BitmapImage.DecodePixelWidth to the width of the monitor, it's crisp enough (even scaled to the second monitor), while keeping the memory footprint far lower than the height*4 x width*4

**Comment by pvginkel** [comment]
Why don't you just use the ControlHost approach? Pdfium (the core dll we
depend on) is optimised for GDI. This is in no way compatible with WPF. I
guess that's the reason you're working with BMPs. However if you just host
the PdfRenderer control in a ControlHost, you get the same performance and
memory usage a WinForms application would have.

**Comment by sbrickey** [comment]
> Why don't you just use the ControlHost approach?

two reasons:
- the control didn't expose some of the properties/events that we needed (scrollbar)
- the control keeps a file lock, whereas converting to images allows the Pdfium objects to be disposed

dealing w/ the scroll would be possible (add some code to your source, possibly submit as a diff/PR)... the file lock *can* be dealt with (I'd probably focus on reading the file into a DeflatedStream in memory, just to try to reduce the footprint if the file is >100kb)... but the cumulative amount of effort exceeded my threshold for this project... quicker to try to fiddle with render settings and just handle the rest in WPF.

**Comment by pvginkel** [comment]
Why is the file lock an issue?

**Comment by peter0302** [comment]
I'm having a similar issue insofar as trying to zoom in on very large PDFs results in huge memory usage because - as far as I can tell - the ENTIRE page has to be rendered by PDFium even if only a subset is going to be visible.

Is there no way in PDFium to only render the RECT that is going to be displayed? Seems like there should be. I tried playing with clipping masks but no matter what PDFium seems to insist on rendering the entire page. Any ideas?

Thanks!

**Comment by pvginkel** [comment]
Well, the core problem here is that the pdf library is not designed for
WPF. Rendering the whole page into memory really is just a hack. The pdfium
library is GDI+, which is not compatible with WPF unless you use a
ControlHost. Maybe pdfium supports a different output format; maybe EMF,
bit then you're just replacing ask of the functionality of this project and
it'd be better to just start from scratch. Sorry, no good news.

**Comment by pvginkel** [comment]
I've had another look at this, and you should be able to render part of the page. What you do is create a `Bitmap` yourself, and a `Graphics` for that, and call a `Render` overload that takes a `Rectangle`. That way you can create a bitmap that's exactly the size you need and only have to have that rendered.

**Comment by sbrickey** [comment]
in case anyone else cares, I've posted the code I used : http://sbrickey.codeplex.com/SourceControl/latest#Libraries/WPF/Controls/ucPdfiumDocumentViewer.cs

it's not completely MVVM/INPC... it provides a Load() method with several overloads to provide filepath / stream / etc... it renders each page into memory (so memory usage relative to the number of pages in PDF), and relative to the screen resolution (so memory usage also relative to max monitor resolution)... the rendered pages are then loaded into Image controls in a StackPanel in a ScrollViewer (via control inheritance).

the result: No file locks, images look good on any monitor (since it picks the max monitor's resolution), scroll position/events are exposed... may or may not fit other peoples' needs, but that's why it's provided to the world :)

**Comment by pvginkel** [comment]
Yup, something like that was what I was thinking of. I'll see whether I can incorporate this into the WPF demo that's in the project. That can use some love anyway.

**Comment by Eagle3386** [comment]
@sbrickey since you provided us with your awesome user control (BTW: Thanks for sharing! 👍) here, I'm asking here instead of over at CodePlex.

The control crashes with the exception "Cannot access a closed Stream." within `private void LoadPage(int pageNumber)` when reaching the following `using`:

```csharp
using (var img = pdfDoc.Render(
                    page: pageNumber - 1,
                    width: RenderWidth,
                    height: RenderHeight,
                    dpiX: 96.0f,
                    dpiY: 96.0f,
                    flags: PdfRenderFlags.None
                ))
```

I'm invoking your user control like this:
```csharp
namespace Yoda.Frontend.Views
{
    using System.Globalization;
    using System.Windows.Markup;

    using SBrickey.Libraries.WPF.Controls;

    public partial class PdfView
    {
        public PdfView(byte[] pdfData)
        {
            this.PdfCanvas = new ucPdfiumDocumentViewer();
            this.PdfCanvas.Load(pdfData);

            InitializeComponent();
        }
    }
}
```

And my window is defined like this:
```xaml
<Window x:Class="Yoda.Frontend.Views.PdfView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:uc="clr-namespace:SBrickey.Libraries.WPF.Controls"
        Height="600" Width="600" Title="PdfView">
  <uc:ucPdfiumDocumentViewer x:Name="PdfCanvas" />
</Window>
```

I'd appreciate any help as I'm new to user controls.

**Comment by Eagle3386** [comment]
Nevermind, I've found the real culprit inside the NativeMethods.Pdfium.cs and opened a [separate issue](https://github.com/pvginkel/PdfiumViewer/issues/86) for it.
