### ISSUE TITLE
Signature fields

### ISSUE THREAD

**Issue by dheijl** [pvginkel/PdfiumViewer#43]
The current version does (by default) not show fields with a digital signature.

Is there a way to get those fields shown, or is the functionality currently unavailable?

An excellent piece of work, it took me about 1 minute to get a pdf file showing, zoomed to "fit width", in a new form!

**Comment by pvginkel** [comment]
A change has been made that renders form fields. Can you verify whether this change fixes your issue?

**Comment by dheijl** [comment]
I'll try this first thing monday morning, thanks!

**Comment by dheijl** [comment]
I can confirm that signature fields are now showing in the PdfiumViewer control.

Thanks!

**Comment by pvginkel** [comment]
That's great to hear.

**Comment by dheijl** [comment]
However, the "print" button in the PdfiumViewer control does not render the form fields.

**Comment by pvginkel** [comment]
I've created #44 for this and I'll try to pick this up ASAP. Sorry for the half solution.

**Comment by dheijl** [comment]
Thanks again!
