### ISSUE TITLE
Printing does not show annotations

### ISSUE THREAD

**Issue by pvginkel** [pvginkel/PdfiumViewer#44]
Through #38 and #43, missing annotations (i.e. filled form fields and signatures) were fixed and are now rendered. However, this does not yet work for printing.

**Comment by dheijl** [comment]
In a quick test using the source code, applying the following change in PdfPrintDocument (line 86) seems to fix it:

                   _document.Render(
                    _currentPage++,
                    e.Graphics,
                    e.Graphics.DpiX,
                    e.Graphics.DpiY,
                    new Rectangle(
                        AdjustDpi(e.Graphics.DpiX, left),
                        AdjustDpi(e.Graphics.DpiY, top),
                        AdjustDpi(e.Graphics.DpiX, width),
                        AdjustDpi(e.Graphics.DpiY, height)
                    ),
                    PdfRenderFlags.ForPrinting | PdfRenderFlags.Annotations
                );

**Comment by pvginkel** [comment]
I've applied this fixed and pushed a new version to NuGet.

**Comment by dheijl** [comment]
Thanks again!
