### ISSUE TITLE
Dispose of PdfRenderer does not properly clean up Document

### ISSUE THREAD

**Issue by interware** [pvginkel/PdfiumViewer#45]
When calling PdfViewer.Dispose() and/or PdfRenderer.Dispose(),  documents previously loaded with the Renderer are not properly disposed off, making it impossible to delete these documents.

**Comment by dheijl** [comment]
This seems to do the trick:

            if (pdfViewer.Document != null) {
                pdfViewer.Document.Dispose();
                pdfViewer.Document = null;
            }
            pdfViewer.Renderer.Invalidate();

**Comment by pvginkel** [comment]
The point is that the `PdfViewer` class does not take ownership of the `PdfDocument`, as it probably shouldn't. I've taken a look at `System.Windows.Forms.PictureBox` as an example. This control shows an `Image`. When the control is disposed, the `Image` is not automatically disposed with it. It seems that this is expected way of working.

An alternative to the above code sample is the following:

    pdfViewer.Disposed += (s, e) => ((PdfViewer)s).Document.Dispose();

You can add this in the constructor and may be easier to use.

**Comment by rearintok** [comment]
i try the code by dheijl..but when i load again the another pdf from stream the document wont show

heres my code

Public Sub LoadPdf(pdfBytes As Byte())
            '//load bytes to stream
            Dim stream = New MemoryStream(pdfBytes)
            LoadPdf(stream)
        End Sub

        Public Sub LoadPdf(stream As Stream)
            '//create PDF Document
            Dim pdfDoc = PdfDocument.Load(stream)
            _document = pdfDoc
            '//load PDF Document into PdfRenderer control
            PdfRenderer.Load(_document)
            UpdateEnabled()
        End Sub

**Comment by pvginkel** [comment]
Sorry for the late reply. The behaviour in the original report is correct.
The point is that the control doesn't take ownership. If you eg look at the
.NET picture control, that does the same with the image object. The last
problem described here i don't really understand. There doesn't seen to be
a problem with the code.

**Comment by rearintok** [comment]
thanks for your reply...i will just use Hide() if the stream is null and disable my toolbars and Show() if doesn't.... disposing the old document and introducing another stream from Sql Server, doesn't work for me, the new stream wont show... BTW thanks again
