### ISSUE TITLE
Render only renders the first page

### ISSUE THREAD

**Issue by firesoul453** [pvginkel/PdfiumViewer#46]
Using PdfDocument.Render only renders the first page and the other pages rener blank.

Any suggestions?

**Comment by pvginkel** [comment]
Sorry for the late reply. It's difficult to help based on this limited information. In general all pages are rendered.

Can you provide an example document that reproduces this issue?

**Comment by firesoul453** [comment]
Hello,
Thanks for releasing this, it has been helpful. I don't know the exactly what the problem is but I got it working by giving every single page it own entire copy of the PDF in memory. Unfortunately I don't have the PDF in question anymore. 

Perhaps I was/am using it wrong? Not sure.

**Comment by pvginkel** [comment]
I have never seen this specific issue before so without a PDF document to reproduce this problem, it'll be difficult for me to solve the problem. If you encounter such a document again, don't hesitate to file a new bug.

**Comment by nikizh** [comment]
I've seen this problem a couple of times using this PDF file - [MultiSizePagePdf.pdf](https://github.com/pvginkel/PdfiumViewer/files/79231/MultiSizePagePdf.pdf). However, it's not 100% reproducible. I'm using rendering logic similar to the one in the WPF example app.

**Comment by pvginkel** [comment]
Does this mean you're not using the `PdfViewer` or `PdfRenderer` component? If that's the case, there is a very good change the problem is in the way you're calling the `PdfDocument` methods. I've never seen such issues in either the `PdfViewer` or `PdfRenderer` component.

Are you able to share your implementation?
