### ISSUE TITLE
Problem loading viewer

### ISSUE THREAD

**Issue by gotnetdude** [pvginkel/PdfiumViewer#48]
I'm a first time user of the PDFiumViewer.  I Installed the viewer as instructed and have included image file demonstrating my setup.  I believe the viewer is installed correctly and the problem is related to my lack of knowledge on how to use of the control.  I have attached 2 image files that contain my code and show the error message I'm receiving.  A couple of additional pieces of information about my setup.  The project was developed with vs 2010,  the os is window 7,  vm 9x.
I'm hoping there is simple explanation.  Thanks in advanced for the assistance in this matter. 

![pdfiumviewer error 1](https://cloud.githubusercontent.com/assets/15858030/11169281/1bca452c-8b81-11e5-90f3-2ddb73db414c.JPG)
![pdfiumviewer error 2](https://cloud.githubusercontent.com/assets/15858030/11169280/1bca0170-8b81-11e5-9dea-090a341f1258.JPG)
![pdfiumviewer error 3](https://cloud.githubusercontent.com/assets/15858030/11169283/1bccac5e-8b81-11e5-8e3a-452271a09dba.JPG)
![pdfiumviewer error 4](https://cloud.githubusercontent.com/assets/15858030/11169282/1bcad94c-8b81-11e5-9844-bfb5ef63099b.JPG)

**Comment by gotnetdude** [comment]
I got the following code to work, but would like to know how to load the pdf to the view so that the user can zoom in and out.  Is there user documentation somewhere?

        private void btnOpenFile_Click(object sender, EventArgs e)
        {
            string strId = gridViewMain.SelectedRows[0].Cells["id"].Value.ToString();

            if (!string.IsNullOrEmpty(strId))
            {
            
                SqlCommand cmd = new SqlCommand(strQuery_GetAttachmentById, objConn);
                cmd.Parameters.AddWithValue("@attachId", strId);
               
                SqlDataAdapter da = new SqlDataAdapter(cmd);
               
                DataTable dt = new DataTable();
              
                da.MissingSchemaAction = MissingSchemaAction.AddWithKey;
                SqlCommandBuilder sqlCmdBuilder = new SqlCommandBuilder(da);
               
                da.Fill(dt);
               
                DataRow dr = dt.Rows[0];

                byte[] PDFBytes = (byte[])dr["attachment"];
                LoadPdf(PDFBytes);
            }
           
        }

        public void LoadPdf(byte[] pdfBytes)
        {
            var PDFstream = new MemoryStream(pdfBytes);
            LoadPdf(PDFstream);
        }

        public void LoadPdf(Stream pdfstream)
        {
            // Create PDF Document
            var pdfDocument = PdfDocument.Load(pdfstream);

            // Load PDF Document into WinForms Control
            pdfRenderer1.Load(pdfDocument);    
        }
    }

**Comment by pvginkel** [comment]
The `PdfViewer` has a `Document` property. You should just be able to assign the `pdfDocument` to this property. You don't need a separate `PdfRenderer` for this since the purpose of `PdfViewer` is to host a `PdfRenderer`, providing extra functionality. However, zoom should just work with `PdfRenderer` using `Ctrl+Scroll`. Another option is to have a look at the source code of `PdfViewer`. This will show you what methods/properties you need to use to implement e.g. zoom yourself. This last option is actually the preferred option because this allows you to fully customize your experience.

**Comment by pvginkel** [comment]
Have you had a chance to look at this?

**Comment by gotnetdude** [comment]
Yes, I appreciate your assistance in this matter..  The viewer is working for me now.  I have not made any modification to the base solution yet. I may have to in the future, but right now I'm focusing on other pressing issues.  

Thanks again...
