### ISSUE TITLE
64bit support?

### ISSUE THREAD

**Issue by iamcarbon** [pvginkel/PdfiumViewer#5]
Is 64bit support planned using a 64bit build of pdfium.dll? This would be useful to use the library to render pdf previews on windows server.

**Comment by pvginkel** [comment]
The reason the library is 32-bit is that there is a dependency to a native DLL, which is 32-bit. However, I will have a look at the option to also make a 64-bit version of the library avialable.

**Comment by pvginkel** [comment]
64-bit support has been added. See the instructions in the README on the main project page for instructions on how to use this.
