### ISSUE TITLE
PdfPrintDocument hides the printing events

### ISSUE THREAD

**Issue by MarManiak** [pvginkel/PdfiumViewer#50]
Just curious about the decision to override the OnBeginPrint, OnQueryPageSettings and OnPrintPage functions in PdfPrintDocument rather than simply using the delegate model and registering functions to be called for those events?  By overriding the OnXXX funcitons, you have removed the ability for anyone using the PdfViewer control to add any specialized printing functions.  For example, I have a program that prints documents without displaying the print dialog.  There are settings within my program that allow the end user to choose what printer to use and what settings to use for the printer and I set that info myself before calling Print().  I now have a need to print the first page of a document from a different paper tray than the remaining pages.  In order to do that, I need to be able to handle the QueryPageSettings and PrintPage events so that I can change the paper source as desired.  I have already tested whether this would work with your PdfPrintDocument class and by changing the code from overriding the OnXXX functions, to using the delegate model, I get exactly the functionality that I need.  I have attached my version of PdfPrintDocument.cs for your review.

[PdfPrintDocument.cs.txt](https://github.com/pvginkel/PdfiumViewer/files/53217/PdfPrintDocument.cs.txt)

**Comment by pvginkel** [comment]
Ah, that's just a mistake on my part. I've added the `base` calls to the end of the existing methods. For `QueryPageSettings` and `PrintPage` I've also added a `Before...` version that's called at the start of the method.

**Comment by MarManiak** [comment]
awesome... is the new version available as a NuGet package?

**Comment by pvginkel** [comment]
Yup.
