### ISSUE TITLE
Pdfium.Net SDK 

### ISSUE THREAD

**Issue by mslissap** [pvginkel/PdfiumViewer#51]
Question - Does this work with the Pdfium.Net SDK NuGet package or do you still need to compile the SDK?

**Comment by pvginkel** [comment]
I'm not sure what your asking. This library has no dependencies and the
pdfium dll is included in its nuget package and the git repository.

**Comment by mslissap** [comment]
On the instructions, there are steps to build Pdfium. I am having trouble building it and wondered if it was still required since there is now a Nuget package for Pdfium.Net SDK. It looks like I will still need to build it.

**Comment by pvginkel** [comment]
Well, those are for when you want to build it. As I said, a pre-compiled
version is in the Git repository and in the nuget package. If you just want
to us the PdfiumViewer control, you don't need to build pdfium yourself.

**Comment by mslissap** [comment]
Ok, thank you! I read it wrong.

**Comment by pvginkel** [comment]
You're welcome. Not a problem.
