### ISSUE TITLE
Trimmed bookmark titles

### ISSUE THREAD

**Issue by xtomino** [pvginkel/PdfiumViewer#54]
From version 2.8.0.0 PdfiumViewer trim last character from bookmark titles. Problem is in **PdfFile.cs** - native method **FPDF_BookmarkGetTitle** returns real bookmark title and trimming last character is useless.

```
private string GetBookmarkTitle(IntPtr bookmark)
{
      uint length = NativeMethods.FPDF_BookmarkGetTitle(bookmark, null, 0);
      byte[] buffer = new byte[length];
      NativeMethods.FPDF_BookmarkGetTitle(bookmark, buffer, length);

      string result = Encoding.Unicode.GetString(buffer);
      return result.Substring(0, result.Length - 1);
}
```
![image](https://cloud.githubusercontent.com/assets/17108003/12872052/766c0d60-cd96-11e5-8fc3-61dd1182a766.png)

**Comment by sforsteruk** [comment]
I believe a related problem is shown with the attached file - it appears to contain zero length bookmarks which causes the code shown to throw an exception, "Length cannot be zero" on the SubString. 

See  
[rdc9_deployment.pdf](https://github.com/pvginkel/PdfiumViewer/files/227615/rdc9_deployment.pdf)

However I'm not sure if this PDF would be considered malformed?

**Comment by xtomino** [comment]
I think that the PDF file is fine. Generally - bookmark title can have a zero length. Our **problem is at last line** in method **GetBookmarkTitle**, because _second argument of Substring function can not be less then zero_!

`return result.Substring(0, result.Length - 1);`

Triming last character on each bookmark title and zero length bookmarks can be resolved by modifying method **GetBookmarkTitle**:

```
private string GetBookmarkTitle(IntPtr bookmark)
{
     uint length = NativeMethods.FPDF_BookmarkGetTitle(bookmark, null, 0);
     byte[] buffer = new byte[length];
     NativeMethods.FPDF_BookmarkGetTitle(bookmark, buffer, length);

     return Encoding.Unicode.GetString(buffer);
}
```

**Comment by pvginkel** [comment]
That's dumb. Don't know why I did that. Has been fixed now.
