### ISSUE TITLE
Increase private const ZoomMax?

### ISSUE THREAD

**Issue by BrsVgl** [pvginkel/PdfiumViewer#55]
Hallo Pieter,

firstly thank you so much for providing this great control.
My only problem is the max zoom value for which the underlying reason is something else:
The problem is that the initial zoom value when loading a document is always 1 and not the "true" zoom value relative to the size of the document. 
I am sure you had your reasons for that behaviour - because you also calculate the "true" zoom internally. But it basically means that when having a large document and/or a relatively small initial size of the control your document only gets opened with maybe 20% of its original size and you are not able to zoom it to more than 100% of its size.

Is there a need for a max value at all? And if so would it not at least be possible to increase it to something like 100?

Thanks for reading,
Boris

**Comment by pvginkel** [comment]
Yeah, you do want a max to prevent users from getting lost. However I have
no problem with increasing the value. I hope I can find the time to do this
soon, but I'm not sure.

**Comment by BrsVgl** [comment]
Hi Pieter,
thanks for the quick reply. I totally agree that the user should be prevented from getting lost. But IMHO this should be done by the developer using the control and not in such a rather restrictive way. But despite this a simple increase would help me a lot.

**Comment by pvginkel** [comment]
I've changed `ZoomIn` and `ZoomOut` to be settable properties.
