### ISSUE TITLE
Rotating and saving the rotated PDF

### ISSUE THREAD

**Issue by rearintok** [pvginkel/PdfiumViewer#56]
Hi, I notice when you rotate a PDF and try to save the changes, nothing happens, how do you save the changes you made on a PDF Document.

**Comment by pvginkel** [comment]
PdfiumViewer does not support modifying PDF's. Such functionality is implemented in very different libraries, e.g. iTextSharp. I don't know whether this library supports rotating PDF's, but I'd suggest having a look there. The save button in the demo application just saves the original PDF document.

**Comment by peter0302** [comment]
Just FYI. The pdfium dll does have the ability to modify and even create new pdf files without needing any other libraries. The functions are very poorly documented but they do work.  I've been using it to merge PDFs and create new ones from images. If anyone wants some tips to I'm happy to share.

On Feb 20, 2016, at 11:48 PM, Pieter van Ginkel <notifications@github.com<mailto:notifications@github.com>> wrote:


PdfiumViewer does not support modifying PDF's. Such functionality is implemented in very different libraries, e.g. iTextSharp. I don't know whether this library supports rotating PDF's, but I'd suggest having a look there. The save button in the demo application just saves the original PDF document.

-

**Comment by pvginkel** [comment]
Ah, clearly i didn't know that :). If you can tell me what apis to use or
can provide a pul request, I could take a look.
