### ISSUE TITLE
Question - zooming without Ctrl

### ISSUE THREAD

**Issue by colinbashbash** [pvginkel/PdfiumViewer#58]
Is it possible to change a setting on the viewer to allow the Mouse Scroll Wheel to Zoom rather than to scroll the document? (I see that it does this normally when you're holding Control)

**Comment by colinbashbash** [comment]
ok, it looks like I can override the PanningZoomingScrollControl to do this. Let me know if I should submit a pull request. I just created a ScrollTypeEnum : PanOnScroll_ZoomOnCtrlScroll, PanOnCtrlScroll_ZoomOnScroll

**Comment by pvginkel** [comment]
I've added a property `MouseWheelMode` that allows the mode to be changed. If that's set to `Zoom`, the mouse wheel only zooms and doesn't look at whether the control is down.
