### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by frankhommers** [pvginkel/PdfiumViewer#62]
Is text selection possible or is it a new feature?

(And after text selection, copy to clipboard)?

**Comment by pvginkel** [comment]
That would be quite a bit of work to implement and regrettably I do not
have time for that in the near future. I do welcome pull requests though.

**Comment by thakurarun** [comment]
Hi @frankhommers ,

Did you implemented the Text Selection. I need this to be implemented for the Search Text in the PDF.

Thanks.

**Comment by frankhommers** [comment]
@thakurarun No I did not. Did you?
