### ISSUE TITLE
File unload

### ISSUE THREAD

**Issue by Ravindran001** [pvginkel/PdfiumViewer#64]
How to unload the pdf file, while delete the file after showing pdf, File access error occur. I am Dispose function also used. it not worked.

**Comment by pvginkel** [comment]
This should just work. Could you possibly provide a code sample that
demonstrates the problem?

**Comment by Ravindran001** [comment]
# Sample code:
 PDFviewer1.Document = PdfiumViewer.PdfDocument.Load(FileName)
{

# Some codes...
}

  if File.exist(FileName) then
		File.Delete(FileName)
  End if
  
Error Shows:
  The process cannot access the file 'File Path' because it is being used by another process.

**Comment by pvginkel** [comment]
What I'm missing is the Dispose call of PDFviewer1.Document. You do need to
dispose that before you can delete the file.

**Comment by Ravindran001** [comment]
I tried with dispose call but the error exist the same

PDFviewer1.Document = PdfiumViewer.PdfDocument.Load(FileName)
 {
 Some codes...

 }
PDFviewer1.Dispose()    'using dispose call
 if File.exist(FileName) then
 File.Delete(FileName)
 End if

 Error Shows:
 The process cannot access the file 'File Path' because it is being used by
 another process.

**Comment by pvginkel** [comment]
The stream was not correctly disposed. This should have been solved. I'm creating a new version in a moment. Please let me know if that didn't solve your issue.
