### ISSUE TITLE
ASP.NET MVC: pdfium.dll locked by iis

### ISSUE THREAD

**Issue by mboltuc** [pvginkel/PdfiumViewer#65]
Hi,

I have an asp.net mvc website that attempts to render a tumbnail of a pdf.  Your library works great for this, however it appears that IIS is holding onto the pdfium.dll.  The code I'm running looks something like below (using 2.9.0.0 nuget package of pdfiumviewer):

`public ActionResult Thumbnail(int documentId)
{
    var imageStream = new MemoryStream();
    using (var stream = new FileStream("path/to/file.pdf", FileMode.Open, FileAccess.Read, FileShare.Read))
    using (var pdfDoc = PdfDocument.Load(stream))
    using (var image = pdfDoc.Render(0, 183, 225, 96, 96, false))
      {
        image.Save(imageStream, ImageFormat.Png);
      }
      imageStream.Position = 0;
      return new FileStreamResult(imageStream, "image/png");
    }`

Any help would be appreciated. Thanks!

**Comment by mboltuc** [comment]
Let me try that again... code sample:
```csharp
    public ActionResult Thumbnail(int documentId)
    {
      var imageStream = new MemoryStream();
      using (var stream = new FileStream("path/to/file.pdf", FileMode.Open, FileAccess.Read, FileShare.Read))
      using (var pdfDoc = PdfDocument.Load(stream))
      using (var image = pdfDoc.Render(0, 183, 225, 96, 96, false))
      {
        image.Save(imageStream, ImageFormat.Png);
      }
      imageStream.Position = 0;
      return new FileStreamResult(imageStream, "image/png");
    }
```

**Comment by pvginkel** [comment]
I think that's normal behavior. Why would you expect iis to release the
native dll? If it would work like that, theoretically iis would have to
reload the native dll on every call or something like that, which would
destroy performance.

Why is it a problem that iis is holding on to the native dll?

**Comment by mboltuc** [comment]
The issue comes when it's time to deploy the website.  I'm using msdeploy to update the site and I get an error about pdfium.dll being in use.  Taking the site offline didn't seem to help, I had to restart the IIS service to get it to be released.  Also, same issue occurs during development builds while the site is running in iisexpress.

**Comment by pvginkel** [comment]
I've had a look on Google and this should be something you could do
yourself. What you should do is before you do anything with PdfiumViewer,
you do a LoadLibrary pinvoke call on the dll. That gives you a handle. You
could do this in the Application_Start. Then as you're unloading the
application, e.g. in Application_End, you call CloseHandle on the handle
you got when loading. This should release the dll. See
http://stackoverflow.com/questions/2445536/unload-a-dll-loaded-using-dllimport
for more info.

**Comment by mboltuc** [comment]
Nice! I will give that a try.   Thanks for the help.

**Comment by NextAlexM** [comment]
@mboltuc Are you able to provide how you fixed this if you did?
