### ISSUE TITLE
Rotation Issue

### ISSUE THREAD

**Issue by xmaux72** [pvginkel/PdfiumViewer#71]
Hello,

I tried to rotate a pdf with the new method included in 2.10.0.0 version

```
var document = PdfDocument.Load(pdfPath);
for (int pageNum = 0; pageNum < document.PageCount; ++pageNum)
{
    document.RotatePage(pageNum, PdfRotation.Rotate90);
}
```

but i get this error. Should I build an updated version of pdfium.dll, following your instructions? Or do you know where I can find binaries?

Thanks,

Maurizio

```
System.EntryPointNotFoundException non è stata gestita
  HResult=-2146233053
  Message=Unable to find an entry point named 'FPDFPage_SetRotation' in DLL 'pdfium.dll'.
  Source=PdfiumViewer
  TypeName=""
  StackTrace:
       at PdfiumViewer.NativeMethods.Imports.FPDFPage_SetRotation(IntPtr page, Int32 rotate)
       at PdfiumViewer.NativeMethods.FPDFPage_SetRotation(IntPtr page, PdfRotation rotation)
       at PdfiumViewer.PdfFile.RotatePage(Int32 pageNumber, PdfRotation rotation)
       at PdfiumViewer.PdfDocument.RotatePage(Int32 pageNumber, PdfRotation rotation)
       at ESLPdfPrint.Program.Main(String[] args) in 
```

**Comment by xmaux72** [comment]
After some investigating:

the problem is not your embedded pdfium.dll but the x86 version of the lib and your new methods in "Imports" class.

The 64bit version is ok, because the 64bit DLL exports are undecorated
```
FPDFPage_SetCropBox
FPDFPage_SetMediaBox
FPDFPage_SetRotation
```

while the 32 bit are:
```
_FPDFPage_SetCropBox@20
_FPDFPage_SetMediaBox@20
_FPDFPage_SetRotation@8
```

probably the issue is the declaration of new methods that differs from previous ones
```c#
[DllImport("pdfium.dll", EntryPoint = "FPDFPage_SetRotation", CallingConvention = CallingConvention.Cdecl)]
```
Thank you for your job

Maurizio

**Comment by pvginkel** [comment]
Thanks for the report. I've fixed the `DllImport`'s and it seems to be working now.
