### ISSUE TITLE
Formatted documentation

### ISSUE THREAD

**Issue by cipri-tom** [pvginkel/PdfiumViewer#72]
Hi,

Thank you so much for this wrapper! Big money saver :heart: !
I was wondering if there is any way of viewing the documentation other than browsing the source files :grinning: ?

Thank you!

**Comment by pvginkel** [comment]
Thanks. I don't have anything up for the documentation. Easiest is to use
the demo application and check there how feature are used. Is there a
specific are you're missing documentation?

**Comment by cipri-tom** [comment]
Nothing specific. I just noticed that there is nice `summary` for every method and wondered if you've rendered that to some MSDN-like website to have a quick reference of features.
I've seen [this SO answer](http://stackoverflow.com/a/14420174/786559) with suggestions on how to generate one, but then it's also a thing to host and maintain it. 

Thank you, once more!
