### ISSUE TITLE
Failed to save

### ISSUE THREAD

**Issue by unholyHub** [pvginkel/PdfiumViewer#73]
When using the Diskette Icon it says:

Could not save the PDF file to the specified location.

And when I use programmatically:

this.pdfViewer.Document.Save("example.pdf");

it gives me: Unable to find an entry point named 'FPDF_SaveAsCopy' in DLL 'pdfium.dll'.

**Comment by cravedevelopment** [comment]
Hi I am experiencing the same problem mentioned above. Is there anyone already solved this issue?

**Comment by cravedevelopment** [comment]
Ignore my first comment. I solved it and it was my project using .NET 4.5. When I changed it to 4.0 it worked! My next question is why it does not support 4.5?

**Comment by vigosser** [comment]
I have the similar issues when change the compiling selection form anyCPU to x86.

My solution is change the DLLImport codes in "NativeMethods.Pdfium.cs", line 718.

replace:
[DllImport("pdfium.dll", EntryPoint = "FPDF_SaveAsCopy", CallingConvention = CallingConvention.Cdecl)]
using:
[DllImport("pdfium.dll")]//it works in the x86 platform

then it works. But I don't know why.

**Comment by pvginkel** [comment]
The `DllImport`'s have been fixed through #71.
