### ISSUE TITLE
Multiple Page Printout Support

### ISSUE THREAD

**Issue by tapaccos** [pvginkel/PdfiumViewer#76]
Hi there
Thanks for the amazing library.

Was wondering if Multiple Page Printout Support capability could be built in.
I tried creating another class for PdfPrintDocument allowing for multiple pages to be printing in one.
However the lack of control of the render functions in PDFDocument prevent one page appearing below the other
bool arg_DA_0 = this._file.RenderPDFPageToDC(page, hdc, (int)dpiX, (int)dpiY, **0, 0**, bounds.Width, bounds.Height, this.FlagsToFPDFFlags(flags));
                NativeMethods.SetViewportOrgEx(hdc, pOINT.X, pOINT.Y, out pOINT);

Namely boundsOriginX and boundsOriginY could exposed in the above function rather than set 0,0
So if we could have a overloaded function with the above in the function call

Thanks again

**Comment by tapaccos** [comment]
I would do this work myself, but I only have sharpdevelop so unable to builld solution.

**Comment by pvginkel** [comment]
I've implemented support for this with an example in the demo application.

I don't know how to extend the print dialog, so this is not properly integrated into the standard printing system. However, the demo application shows how this functionality can be used, but would require you to implement a dialog yourself asking the user how to layout the pages.
