### ISSUE TITLE
Text search in PdfiumViewer 

### ISSUE THREAD

**Issue by incity** [pvginkel/PdfiumViewer#78]
Hi, i implement the text search base on your project, but it doesnt work anyway...
Here's my implementaion, can u tell me what's wrong with it???
`PdfMatches matches = pdfViewer1.Document.Search(_search.Text, false, false, 0);`
`if(matches.Items.Count>0)` 
     `pdfViewer1.Renderer.Page = matches.Items[0].Page;`
The matches.Items.Count alway equal to 0 whatever text i search.

**Comment by pvginkel** [comment]
I've added some demo code. Please see the attached commit above, which seems to work fine.
