### ISSUE TITLE
Render to Bitmaps

### ISSUE THREAD

**Issue by fdncred** [pvginkel/PdfiumViewer#79]
In case anyone needs to render to bitmaps at a resolution other than 96 DPI here's how you do it. Change the Render method in PdfDocument.cs to this.

```
public Image Render(int page, int width, int height, float dpiX, float dpiY, PdfRenderFlags flags)
{
    if (_disposed)
        throw new ObjectDisposedException(GetType().Name);

    // This is what renders the image at the proper width/height/resolution
    width = width / 72 * (int)dpiX;
    height = height / 72 * (int)dpiY;
    // The rest of the method is unchanged
```

The reason it's divided by 72 is because Pdf files default to points not inches and there are 72 points in 1 inch.

Thanks for the code and good luck!

**Comment by pvginkel** [comment]
I've added a flag `PdfRenderFlags.CorrectFromDpi` that does this. I find it a bit too scary to implement this as is, but at least this way you can have this logic without having to compile your own PdfiumViewer.
