### ISSUE TITLE
Embedding into single exe

### ISSUE THREAD

**Issue by cipri-tom** [pvginkel/PdfiumViewer#81]
Hi,

Is it possible to embed PdfiumViewer into the `exe` so that the app can be 'portable', without dependencies?
I have tried using Costura.Fody, but somehow the native library cannot be found by PdfiumViewer once this has been embedded.

Thank you!

**Comment by pvginkel** [comment]
I don't know about Fody, but what I would do is add the native dll as an
embedded resource, extract it to a temporary location and do a LoadLibrary
on that. When you close the application, after you make sure all
PdfiumViewer controls are disposed, you can unload the library and delete
it.
