### ISSUE TITLE
Unable to load DLL 'pdfium.dll'

### ISSUE THREAD

**Issue by knarfsavage** [pvginkel/PdfiumViewer#83]
Hi,

I am trying to use the pdfiumViewer on my C# project to display pdfs in a winform.

I downloaded the nuget package and have both x86 and x86 in my application directory as placed by nuget installer. I also made sure i clicked on both DLLs and selected the option to "Always Copy To Output Directory"

I have a method as such :

public void LoadPdf(string path)
        {
            var pdfDocument = PdfiumViewer.PdfDocument.Load(path);
            pdfrenderer.Load(pdfDocument);
        }

It keeps failling on the PdfDocument.Load(Path) with : Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I am using windows 7 64 bit.

Why can't it find the DLL, but i can access all it's functions ?

Thanks for any feedback.

**Comment by pvginkel** [comment]
Have you taken a look at the demo application that's part of the
PdfiumViewer repository? That application is configured correctly and you
should be able to use that as an example.

**Comment by knarfsavage** [comment]
Thank you for your very quick reply ! Will have a look. regards,

**Comment by knarfsavage** [comment]
I am using visual studio 2012 so i can't run your application because i have no C# compiler for c# 6.0. So codes including nameof and Document?.Dispose()  have errors.  But based on your code example, I did the following :

Downloaded the NuGet package, In my main form designer i created the control:

```
 private global::PdfiumViewer.PdfViewer pdfViewer;

this.pdfViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pdfViewer.Enabled = true;
            this.pdfViewer.Location = new System.Drawing.Point(0, 0);
            this.pdfViewer.Name = "pdfPreview";
            this.pdfViewer.Size = new System.Drawing.Size(419, 484);
            this.pdfViewer.TabIndex = 0;

//Then added this to the main control

this.Controls.Add(this.pdfViewer);
 
```

In my main form class constructor, i call the `initialize();`



Then I have the following methods :

```
private PdfDocument OpenDocument(string fileName)
        {
            try
            {
                return PdfDocument.Load(this, fileName);
            }
            catch (Exception ex)
            {
                MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
                return null;
            }
        }
```

Then somewhere i call : `pdfViewer.Document = OpenDocument(path);`


When i execute, i have :

> Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

at :   `return PdfDocument.Load(this, fileName);`


Please bare with me if i am making some very trivail mistake. But it all looks correct from my perspective. Anywhere i can invistigate or am i missing a step ? 

Thanks for your time.

**Comment by pvginkel** [comment]
Probably, but that's OK. Have you put the DLL's in sub folders names x86
and x64 into the root of your project? PdfiumViewer looks for the DLL's in
those directory name relative to the location of the PdfiumViewer DLL
location. So, you should have in your project (the project of the exe it
your application is cut into multiple projects) a bin\Debug\x86\pdfium.dll
and a bin\Debug\x64\pdfium.dll.

**Comment by knarfsavage** [comment]
Thank you Pieter, It works. I did exactly as you adviced. Is it worth mentionining this in your "HOW TO" ? 
Because some like me will think as NuGet downloads the DLLs and creates x86,x64 folders in your project root thats enough.

**Comment by CZahrobsky** [comment]
That dll is not a .NET assembly, so you cannot include it.  I added it as a resource and extracted it next to the PdfiumViewer .NET wrapper:
```
                var pfpath = typeof(PdfDocument).Assembly.Location;
                pfpath = pfpath.Substring(0, pfpath.LastIndexOf("\\") + 1) + "pdfium.dll";
                if (!File.Exists(pfpath))
                {
                    GetResourceFile("pdfium.dll", pfpath);
                }

```

**Comment by paulweight** [comment]
Hi, I am running a VS2017 environment and a X64 only wpf app. I have followed the instructions above . My dir structure is /test/test/bin/X64/pdfifium.dll and  /test/test/bin/X86/pdfifium.dll with  /test/test/bin/X64/Release/Pdfviewer.dll at this location is this correct? 
I added the viewer into a Windows form which will run in my wpf app).

When I try to add it as a reference I get the following... any thoughts?
![error_message](https://user-images.githubusercontent.com/16876842/31810514-fd932154-b573-11e7-82ae-bc52b33f0fba.jpg)

**Comment by dj2480** [comment]
I don't see any x86 and x64 folder in my project. I installed thru NuGet command below.

Install-Package PdfiumViewer -Version 2.13.0

Please let me know if I am missing anything. I am getting below error when i try to run the code. 
**Unable to load DLL 'pdfium.dll': The specified module could not be found.**

I don't see pdfium.dll anywhere in the references. I only see PdfiumViewer.dll.

**Comment by wiera987** [comment]
First, how about reading PdfiumViewer's "README.markdown"?

> Using the library
> 
> The PdfiumViewer control requires native PDFium libraries. These are not included in the PdfiumViewer NuGet package. See the Installation instructions Wiki page for more information on how to add these.
