### ISSUE TITLE
ObjectDisposedException - "Cannot access a closed Stream"

### ISSUE THREAD

**Issue by Eagle3386** [pvginkel/PdfiumViewer#86]
While on my quest to utilize @sbrickey's kindly provided [WPF user control](https://github.com/pvginkel/PdfiumViewer/issues/42#issuecomment-227810939), I experienced the abovementioned exception.

So, I added the PdfiumViewer project and after enabling `System.ObjectDisposedException` in VS settings, I came to the real source of the problem: `stream.Position = position;` within this method:
```csharp
private static int FPDF_GetBlock(IntPtr param, uint position, IntPtr buffer, uint size)
{
  var stream = StreamManager.Get((int)param);
  if (stream == null)
    return 0;
  byte[] managedBuffer = new byte[size];

  stream.Position = position;
  int read = stream.Read(managedBuffer, 0, (int)size);
  if (read != size)
    return 0;

  Marshal.Copy(managedBuffer, 0, buffer, (int)size);
  return 1;
}
```
The file containing it is `Native.Methods.Pdfium.cs` and the problem is an access violation because the `Position` property isn't available whenever the stream is null.

I don't understand while this happens as I don't understand what closes the stream so unexpectedly and why that happens in the first place as the first page(s) are read properly and there are pages left to be rendered, too.

**Comment by pvginkel** [comment]
The problem is in the WPF control:

    public void Load(byte[] fileContents)
    {
        this.LoadPDF(() =>
        {
            using (var ms = new System.IO.MemoryStream(fileContents))
                return PdfDocument.Load(ms);
        });
    }

The stream is disposed, which is not correct. Instead, this should look as follows:

    public void Load(byte[] fileContents)
    {
        this.LoadPDF(() =>
        {
            return PdfDocument.Load(new System.IO.MemoryStream(fileContents));
        });
    }

This doesn't ever dispose the `MemoryStream`, which isn't a problem because, well, it's a `MemoryStream`.

**Comment by Eagle3386** [comment]
Oh, yeah, not solving the issue and just close the issue by stating it's not a problem because it's a `MemoryStream`. Good job - [not](https://stackoverflow.com/questions/4274590/memorystream-close-or-memorystream-dispose#4274769).

Sure, you've got a real life, this is all free source and I could fork it myself - if only I did understand your code better. Or just write my own PDF control in (maybe) pure XAML. Well, I guess, I got to high expectations on you as the maintainer. Sorry about that - really.

**Comment by pvginkel** [comment]
I'm not sure what the problem is. The WPF code is not mine and I can't
change it. It's disposing the steam too early, which is the problem. I told
you how you can fix it.

What do you expect be to do!

**Comment by Eagle3386** [comment]
Mixed up you as the maintainer of the repo and the other guy providing the sample for the using.
I'm honestly sorry about that and edited my comment accordingly. Now, if you do that to your comment, to, I hope the misunderstand between us can get resolved.

Additionally, I didn't mean to sound that harsh. I apologize for being like that.

**Comment by pvginkel** [comment]
No I'm fine. Even if I were the original maintainer, you could still have been a bit nicer.

As for your referenced StackOverflow article:

> `MemoryStream` does not have any unmanaged resources to dispose, so you don't technically have to dispose of it. The effect of not disposing a `MemoryStream` is roughly the same thing as dropping a reference to a `byte[]` -- the GC will clean both up the same way.

So, yes, you can just leave it and not dispose of it. The remarks in the comments (i.e. "making the GC's job easier") is minuscule, as the next person also says: "today's GCs won't show any difference".

**Comment by Eagle3386** [comment]
> No I'm fine.
Thank you. I've hoped you say that.

> Even if I were the original maintainer, you could still have been a bit nicer.
Of course. That's what I try to address with my last paragraph in the comment above yours. I hope you can accept my apologies for that, too. It was unprofessionally and everybody deserves better.

Regarding your remarks about disposing, I'm just aiming for 100% "ethically" correct code. That means while several things are syntactically and also semantically correct, it's not always right to go such roads. Hence I tried to wrap it in a `using` in order to dispose of it just when the code finishes. Unfortunately, `async` gets in the way and I'm not skilled enough (yet) to get both "worlds" working together.
