### ISSUE TITLE
Retreaving file name from the viewer.

### ISSUE THREAD

**Issue by muhammedk** [pvginkel/PdfiumViewer#89]
Hi

I am facing a challenge to retrieve the file name which is loaded in the viewer. I have an application which user is manipulating the PDF and each time I am saving it with different name to keep the history.

Is there any way to get back the file name which is loaded in viewer

**Comment by pvginkel** [comment]
No, there's not. The `PdfViewer`/`PdfRenderer` only keeps the stream, which doesn't have the filename. You have to keep track of this yourself.
