### ISSUE TITLE
-- Highlight Search Text and Previous and Next 

### ISSUE THREAD

**Issue by thakurarun** [pvginkel/PdfiumViewer#91]
Hi,

Could you help me how I can highlight the Search text in the PDF Viewer?
I need also the Previous and next button functionality.

Thanks

**Comment by pvginkel** [comment]
I've implemented a `PdfSearchManager` that provides this functionality and a search dialog in the demo application. This probably implements everything you need, including highlighting. Have a look and please re-open this ticket if you're missing something.
