### ISSUE TITLE
PDF not rendered?

### ISSUE THREAD

**Issue by martinrotter** [pvginkel/PdfiumViewer#99]
![pdfium](https://cloud.githubusercontent.com/assets/1255302/21642653/082e6cdc-d284-11e6-87d2-ff1439235e9d.png)

Relevant code:

```csharp
``` pdfDoc = PdfiumViewer.PdfDocument.Load(msDokument); // memorystream
``` me.Load(this.pdfDoc); // me = PdfiumViewer.PdfRenderer

No exception is thrown, nothing. Just big rectangle instead of PDF itself. Version 2.9.0.0 worked fine. 2.10.0.0 and 2.11.0.0 are broken.

**Comment by martinrotter** [comment]
Is this project dead?

**Comment by pvginkel** [comment]
No, it's not dead. I just have very little spare time to work on this.

Can you please provide me with the PDF document you're trying to load so I can reproduce this issue?

**Comment by aschuhardt** [comment]
Is there any update on this?

**Comment by martinrotter** [comment]
It "works" with any document, when I try to load it with `PdfiumViewer.PdfDocument.Load(stream)` method. Method, which takes path to PDF file, works fine.

So, as a workaround, I have to save every PDF data to file first, and then load it in pdf renderer.

**Comment by IanYates** [comment]
Are you disposing of that stream anywhere?  Perhaps a change was made in `PdfDocument` that expects the stream to hang around for the lifetime of the document?  If not disposing, do you have other code that seeks through that stream independent of the PdfDocument?

**Comment by martinrotter** [comment]
No, it is not disposed at all. Same code works with 2.9, but does not in all newer versions.

**Comment by IanYates** [comment]
Curious.  As @pvginkel asked, are you able to share the PDF at all?
Or is it failing for *every* PDF you try to load as a stream?  If so, can you cut it down to a simple console app and reproduce?

**Comment by martinrotter** [comment]
Every PDF I tried, yes.

**Comment by martinrotter** [comment]
But I am not able to reproduce with 2.12 yet. Considering fixed......
